name: Build OCI Images

on:
  push:
    branches:
      - main
      - js-lib-tests
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Build and push OCI image, tag: tools"
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        file: oci/tools.Containerfile
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tools
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tools-${{github.sha}}

    - name: "Build and push OCI image, tag: tf-tools"
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        file: oci/tools.Containerfile
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tools-tf
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tools-tf-${{github.sha}}

    - name: "Build and push OCI image, tag: tests"
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        file: oci/tests.Containerfile
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tests
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:tests-${{github.sha}}

