name: "Manually-triggered tests"

on:
  workflow_dispatch:
    inputs:
      profiles:
        description: "List of profiles from $PROFILES secret env var"
        type: string
        required: false
        default: "br-ne1,br-se1"
      tests:
        description: "List of test ids, see README for the table, leave empty for ALL"
        type: string
        required: false
        default: ""
      clients:
        description: "List of clients"
        type: string
        required: false
        default: "mgc,aws-s3api,rclone,aws-s3"
      skip_known_issues:
        description: "Skip known issues"
        type: string
        required: false
        default: "yes"

env:
  PROFILES: ${{ secrets.profiles }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: ghcr.io/marmotitude/s3-tester:tests
    steps:
      - name: "Run with tests, clients and profiles from user input"
        run: |
          cd /app
          mgc --version
          sha256sum `which mgc`
          ./entrypoint.sh --profiles ${{ inputs.profiles }} --tests ${{ inputs.tests }} --clients ${{ inputs.clients }} -- --env SKIP_KNOWN_ISSUES=${{ inputs.skip_known_issues }}
