name: "Manual Benchmark test"

on:
  workflow_dispatch:
    inputs:
      profiles:
        description: "List of profiles from $PROFILES secret env var"
        type: string
        required: false
        default: "br-ne1,br-se1"
      clients:
        description: "List of clients"
        type: string
        required: false
        default: "mgc,rclone,aws-s3"
      sizes:
        description: "List of files size"
        type: string
        required: false
        default: "1,10,100"
      quantity:
        description: "List of quantity files"
        type: string
        required: false
        default: "10"
      times:
        description: "Times of run tests"
        type: string
        required: false
        default: "10"
      workers:
        description: "Number of workers to parallelize CLIS"
        type: string
        required: false
        default: "10"
      skip_known_issues:
        description: "Skip known issues"
        type: string
        required: false
        default: "no"

env:
  PROFILES: ${{ secrets.profiles }}


jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: ghcr.io/marmotitude/s3-tester:tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: "Run with tests, clients and profiles from user input"
        run: |
          echo copying specs from the workspace volume to the image workspace...
          cp $GITHUB_WORKSPACE/spec/*.sh /app/spec/.
          cd /app
          echo "$PROFILES" > profiles.yaml
          ./bin/replace_configs.sh
          mgc --version
          ./bin/benchmark-test.sh --profiles ${{ inputs.profiles }} --tests ${{ inputs.tests }} --clients ${{ inputs.clients }} --sizes ${{ inputs.sizes }} --quantity ${{ inputs.quantity }} -- --env NUMBER_OF_WAITS=${{ vars.NUMBER_OF_WAITS }} --env SKIP_KNOWN_ISSUES=${{ inputs.skip_known_issues }} --color
