name: "Manually-triggered clean"

on:
  workflow_dispatch:
    inputs:
      profiles:
        description: "List of profiles from $PROFILES secret env var"
        type: string
        required: false
        default: "br-se1"

env:
  PROFILES: ${{ secrets.profiles }}


jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: ghcr.io/marmotitude/s3-tester:tests
    steps:
      - name: Clean buckets
        continue-on-error: true
        env:
          PROFILES: ${{ secrets.PROFILES }}
        run: |
          cd /app
          echo "$PROFILES" > profiles.yaml
          ./bin/replace_configs.sh
          ./bin/clear_buckets.sh ${{ inputs.profiles }}


          