name: Scheduled test runs

on:
  schedule:
    - cron:  '*/30 * * * *'

env:
  PROFILES: ${{ secrets.profiles }}

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    container: ghcr.io/marmotitude/s3-tester:tests
    steps:
      - name: "Upload, List, Download, Delete"
        run: |
          cd /app
          mgc --version
          sha256sum `which mgc`
          ./entrypoint.sh --profiles "${{ vars.CRON_TEST_PROFILES }}" --tests "${{ vars.CRON_TEST_TESTS}}" --clients "${{ vars.CRON_TEST_CLIENTS }}

