name: Scheduled test runs

on:
  schedule:
    - cron: '30 * * * *'
    - cron: '35 * * * *'

env:
  PROFILES: ${{ secrets.profiles }}

jobs:
  "CRON_TESTS_1":
    runs-on: ubuntu-latest
    container: ghcr.io/marmotitude/s3-tester:tests
    steps:
      - name: "Profiles: ${{ vars.CRON_PROFILES_1 }}; Clients: ${{ vars.CRON_CLIENTS_1}}; Tests: ${{ vars.CRON_TESTS_1 }};"
        if: github.event.schedule == '30 * * * *'
        run: |
          cd /app
          mgc --version
          sha256sum `which mgc`
          ./entrypoint.sh --profiles "${{ vars.CRON_PROFILES_1 }}" --tests "${{ vars.CRON_TESTS_1 }}" --clients "${{ vars.CRON_CLIENTS_1 }}" -- --env SKIP_KNOWN_ISSUES=${{ vars.SKIP_KNOWN_ISSUES }} --color
      - name: "Profiles: ${{ vars.CRON_PROFILES_2 }}; Clients: ${{ vars.CRON_CLIENTS_2}}; Tests: ${{ vars.CRON_TESTS_1 }};"
        if: github.event.schedule == '35 * * * *'
        run: |
          cd /app
          mgc --version
          sha256sum `which mgc`
          ./entrypoint.sh --profiles "${{ vars.CRON_PROFILES_2 }}" --tests "${{ vars.CRON_TESTS_1 }}" --clients "${{ vars.CRON_CLIENTS_2 }}" -- --env SKIP_KNOWN_ISSUES=${{ vars.SKIP_KNOWN_ISSUES }} --color
      - name: Upload results.tap artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-tap
          path: /app/report/results.tap
      - name: webhook send
        if: always()
        run: |
          cd /app
          ./webhook.py "${{ vars.WEBHOOK_URL }}" "${{ github.repository }}" "${{ github.run_id }}"
      - name: CLEAN_BUCKETS
        if: always()
        run: |
          for profile in ${{ vars.PROFILES_TO_CLEAN }}; do
            aws s3 ls --profile $profile | grep "test-" | awk '{print $3}' | while read -r bucket; do
              aws s3 rb s3://$bucket --profile $profile --force
            done
          done

