name: "Automatic clean"

on:
  schedule:
    - cron: '0 * * * *'    # Hourly clean

env:
  PROFILES: ${{ secrets.profiles }}


jobs:
  hourly-clean:
    if: github.event.schedule == '0 * * * *'
    runs-on: ubuntu-latest
    container: ghcr.io/marmotitude/s3-tester:tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Clean buckets
        continue-on-error: true
        env:
          PROFILES: ${{ secrets.PROFILES }}
        run: |
          cd /app
          echo "$PROFILES" > profiles.yaml
          ./bin/replace_configs.sh
          poetry run ./bin/clean_buckets.py br-se1 br-ne1
